import type { Food } from "@/types/food";

export const foodsSeed: Food[] = [
  {
    id: "dog-001",
    brand: "Royal Canin",
    name: "Mini Adult",
    species: "dog",
    lifeStage: "adult",
    activitySupport: "normal",
    healthSupport: ["general"],
    protein: 27,
    fat: 16,
    fiber: 2.5,
    sodium: 0.3,
    magnesium: 0.08,
    calcium: 1.1,
    phosphorus: 0.9,
    ingredients: ["chicken", "rice", "corn"],
    tags: ["adult", "small breed"],
  },
  {
    id: "dog-002",
    brand: "Hill's Science Diet",
    name: "Perfect Weight",
    species: "dog",
    lifeStage: "adult",
    activitySupport: "low",
    healthSupport: ["weight control"],
    protein: 25,
    fat: 11,
    fiber: 9,
    sodium: 0.25,
    magnesium: 0.07,
    calcium: 0.95,
    phosphorus: 0.75,
    ingredients: ["chicken", "barley", "brown rice"],
    tags: ["weight control", "adult"],
  },
  {
    id: "dog-003",
    brand: "Purina Pro Plan",
    name: "Sensitive Skin & Stomach Salmon",
    species: "dog",
    lifeStage: "adult",
    activitySupport: "normal",
    healthSupport: ["sensitive stomach", "skin support"],
    protein: 26,
    fat: 16,
    fiber: 4,
    sodium: 0.28,
    magnesium: 0.06,
    calcium: 1.0,
    phosphorus: 0.8,
    ingredients: ["salmon", "rice", "oatmeal"],
    tags: ["sensitive stomach", "skin support"],
  },
  {
    id: "dog-004",
    brand: "Royal Canin",
    name: "Ageing 12+",
    species: "dog",
    lifeStage: "senior",
    activitySupport: "low",
    healthSupport: ["kidney support", "senior support"],
    protein: 24,
    fat: 12,
    fiber: 5,
    sodium: 0.2,
    magnesium: 0.06,
    calcium: 0.9,
    phosphorus: 0.55,
    ingredients: ["poultry", "rice", "fish oil"],
    tags: ["senior", "kidney aware"],
  },
  {
    id: "dog-005",
    brand: "Acana",
    name: "Puppy Recipe",
    species: "dog",
    lifeStage: "young",
    activitySupport: "high",
    healthSupport: ["growth support"],
    protein: 33,
    fat: 20,
    fiber: 5,
    sodium: 0.35,
    magnesium: 0.09,
    calcium: 1.4,
    phosphorus: 1.1,
    ingredients: ["chicken", "turkey", "eggs", "oats"],
    tags: ["puppy", "high protein", "growth"],
  },
  {
    id: "dog-006",
    brand: "Orijen",
    name: "Original Dog",
    species: "dog",
    lifeStage: "all",
    activitySupport: "high",
    healthSupport: ["general", "muscle support"],
    protein: 38,
    fat: 18,
    fiber: 4,
    sodium: 0.4,
    magnesium: 0.1,
    calcium: 1.3,
    phosphorus: 1.0,
    ingredients: ["chicken", "turkey", "flounder", "eggs"],
    tags: ["all life stages", "high protein"],
  },
  {
    id: "cat-001",
    brand: "Royal Canin",
    name: "Indoor Adult Cat",
    species: "cat",
    lifeStage: "adult",
    activitySupport: "low",
    healthSupport: ["general"],
    protein: 32,
    fat: 14,
    fiber: 5,
    sodium: 0.3,
    magnesium: 0.08,
    calcium: 1.0,
    phosphorus: 0.85,
    ingredients: ["chicken", "rice", "corn"],
    tags: ["indoor", "adult"],
  },
  {
    id: "cat-002",
    brand: "Hill's Science Diet",
    name: "Adult Perfect Weight Cat",
    species: "cat",
    lifeStage: "adult",
    activitySupport: "low",
    healthSupport: ["weight control"],
    protein: 34,
    fat: 10,
    fiber: 8,
    sodium: 0.24,
    magnesium: 0.07,
    calcium: 0.95,
    phosphorus: 0.72,
    ingredients: ["chicken", "pea fiber", "rice"],
    tags: ["weight control", "adult"],
  },
];