import type { ChatbotIntent, DialogueTemplate, PetField } from "@/lib/chatbot/types";

const BASIC_PET_FIELDS: PetField[] = ["species", "age", "weight"];
const SHOPPING_FIELDS: PetField[] = [
  "species",
  "age",
  "weight",
  "neutered",
  "healthIssues",
  "allergies",
];

const commonFollowUps = {
  species: {
    el: "Μιλάμε για σκύλο ή γάτα;",
    en: "Are we talking about a dog or a cat?",
  },
  age: {
    el: "Πόσο χρονών είναι;",
    en: "How old is the pet?",
  },
  weight: {
    el: "Πόσα κιλά είναι περίπου;",
    en: "What is the pet's approximate weight?",
  },
  neutered: {
    el: "Είναι στειρωμένο;",
    en: "Is the pet neutered or sterilised?",
  },
  healthIssues: {
    el: "Υπάρχει κάποιο θέμα υγείας ή ευαισθησία που πρέπει να ξέρω;",
    en: "Any health issue or sensitivity I should know about?",
  },
  allergies: {
    el: "Υπάρχει γνωστή αλλεργία ή συστατικό που θέλεις να αποφύγουμε;",
    en: "Any known allergy or ingredient we should avoid?",
  },
  currentFood: {
    el: "Τι τροφή τρώει τώρα; Αν δεν ξέρεις, γράψε ότι δεν ξέρεις.",
    en: "What food is the pet eating now? If you are not sure, say so.",
  },
  bodyCondition: {
    el: "Θα το έλεγες αδύνατο, κανονικό ή παχουλό;",
    en: "Would you describe the pet as thin, ideal, or overweight?",
  },
  breed: {
    el: "Τι φυλή είναι ή τι μέγεθος σώματος έχει;",
    en: "What breed is it, or what body size?",
  },
  activityLevel: {
    el: "Η δραστηριότητα είναι χαμηλή, κανονική ή υψηλή;",
    en: "Is activity low, normal, or high?",
  },
  vetDiagnosis: {
    el: "Υπάρχει διάγνωση ή σύσταση κτηνιάτρου;",
    en: "Is there a diagnosis or vet recommendation?",
  },
} as const;

const noDiagnosis = [
  "Do not diagnose.",
  "Do not claim treatment or cure.",
  "Use veterinarian guidance for disease cases or red flags.",
];

const sourceConfidenceRules = [
  "High confidence requires matched database food, correct species, life-stage fit, ingredients, kcal, core macros, and relevant minerals.",
  "Medium confidence is allowed when product match is good but some minerals or optional nutrients are missing.",
  "Low confidence when product match is uncertain, source is needs_review, or core pet data is missing.",
  "When nutrient data is missing, say what is missing instead of guessing.",
];

function questions(fields: PetField[]) {
  return {
    el: Object.fromEntries(fields.map((field) => [field, commonFollowUps[field].el])),
    en: Object.fromEntries(fields.map((field) => [field, commonFollowUps[field].en])),
  } as DialogueTemplate["follow_up_questions"];
}

function template(input: DialogueTemplate): DialogueTemplate {
  return input;
}

export const dialoguePlaybook: Record<ChatbotIntent, DialogueTemplate> = {
  food_recommendation: template({
    intent: "food_recommendation",
    intent_group: "shopping",
    required_pet_fields: SHOPPING_FIELDS,
    follow_up_questions: questions(SHOPPING_FIELDS),
    safety_notes: noDiagnosis,
    response_sections: ["direct_answer", "best_fits", "value_options", "why", "watchouts"],
    eligible_logic: [
      "Food species must match pet species.",
      "Life stage should match or be all_life_stages.",
      "Exclude known allergens and explicit disliked proteins.",
      "Prefer recommendable Food V2 rows with stronger data confidence.",
    ],
    rejected_logic: [
      "Reject species mismatch.",
      "Reject known allergen conflict.",
      "Hold low-confidence medical recommendations.",
    ],
    confidence_rules: sourceConfidenceRules,
  }),
  brand_comparison: template({
    intent: "brand_comparison",
    intent_group: "comparison",
    required_pet_fields: ["species", "age", "weight", "healthIssues", "allergies"],
    follow_up_questions: questions(["species", "age", "weight", "healthIssues", "allergies"]),
    safety_notes: noDiagnosis,
    response_sections: ["short_verdict", "side_by_side", "best_for", "not_ideal_for"],
    eligible_logic: ["Compare only matched formulas, not vague brand reputation.", "Use database nutrients and source quality as truth."],
    rejected_logic: ["Do not compare if both products are not resolved enough.", "Do not invent missing nutrient values."],
    confidence_rules: sourceConfidenceRules,
  }),
  ingredient_question: template({
    intent: "ingredient_question",
    intent_group: "ingredient",
    required_pet_fields: ["species", "allergies"],
    follow_up_questions: questions(["species", "allergies"]),
    safety_notes: ["Ingredient lists are interpretation signals, not full nutrition proof.", ...noDiagnosis],
    response_sections: ["what_it_is", "why_it_is_used", "when_to_be_careful", "confidence"],
    eligible_logic: ["Explain ingredient role based on known nutrition function and pet context."],
    rejected_logic: ["Do not declare ingredient good or bad without context.", "Do not diagnose food allergy from symptoms alone."],
    confidence_rules: ["Higher confidence when full ingredient list and pet allergy history are known.", ...sourceConfidenceRules],
  }),
  allergy: template({
    intent: "allergy",
    intent_group: "medical",
    required_pet_fields: ["species", "age", "weight", "allergies", "currentFood"],
    follow_up_questions: questions(["species", "age", "weight", "allergies", "currentFood"]),
    safety_notes: ["Food allergy needs veterinarian-guided elimination trial for confirmation.", ...noDiagnosis],
    response_sections: ["avoid", "safer_shortlist", "trial_logic", "vet_note"],
    eligible_logic: ["Exclude declared allergens.", "Boost hydrolysed, limited ingredient, or novel-protein foods when data supports it."],
    rejected_logic: ["Reject formulas with broad animal derivatives when allergen avoidance requires precision.", "Reject declared allergen conflicts."],
    confidence_rules: ["High confidence requires ingredient text precise enough to exclude allergens.", ...sourceConfidenceRules],
  }),
  sensitive_digestion: template({
    intent: "sensitive_digestion",
    intent_group: "medical",
    required_pet_fields: BASIC_PET_FIELDS.concat(["healthIssues", "currentFood"]),
    follow_up_questions: questions(BASIC_PET_FIELDS.concat(["healthIssues", "currentFood"])),
    safety_notes: ["Persistent vomiting, diarrhea, blood, or weight loss needs veterinarian guidance.", ...noDiagnosis],
    response_sections: ["likely_food_fit", "digestive_supports", "transition_plan", "red_flags"],
    eligible_logic: ["Boost digestive, gastrointestinal, sensitive, prebiotic, beet pulp, psyllium, FOS/MOS signals."],
    rejected_logic: ["Avoid abrupt changes.", "Hold foods with allergy conflicts or very low data confidence."],
    confidence_rules: sourceConfidenceRules,
  }),
  pancreatitis: template({
    intent: "pancreatitis",
    intent_group: "medical",
    required_pet_fields: BASIC_PET_FIELDS.concat(["vetDiagnosis"]),
    follow_up_questions: questions(BASIC_PET_FIELDS.concat(["vetDiagnosis"])),
    safety_notes: ["Pancreatitis requires veterinarian-directed diet selection.", ...noDiagnosis],
    response_sections: ["vet_first", "data_needed", "fat_caution", "safe_next_step"],
    eligible_logic: ["Only discuss low-fat positioning cautiously when diagnosis is already vet-managed."],
    rejected_logic: ["Reject high-fat enthusiasm.", "Do not recommend OTC treatment for pancreatitis."],
    confidence_rules: ["Low confidence without vet diagnosis and fat data.", ...sourceConfidenceRules],
  }),
  renal: template({
    intent: "renal",
    intent_group: "medical",
    required_pet_fields: BASIC_PET_FIELDS.concat(["vetDiagnosis"]),
    follow_up_questions: questions(BASIC_PET_FIELDS.concat(["vetDiagnosis"])),
    safety_notes: ["Renal disease needs veterinarian monitoring and phosphorus-aware diet choice.", ...noDiagnosis],
    response_sections: ["vet_first", "renal_diet_logic", "phosphorus_note", "questions"],
    eligible_logic: ["Prefer renal/veterinary formulas with phosphorus data and official source."],
    rejected_logic: ["Reject casual high-protein recommendations.", "Hold foods missing phosphorus for renal decisions."],
    confidence_rules: ["High confidence requires confirmed renal context and phosphorus data.", ...sourceConfidenceRules],
  }),
  obesity: template({
    intent: "obesity",
    intent_group: "feeding",
    required_pet_fields: BASIC_PET_FIELDS.concat(["neutered", "bodyCondition", "activityLevel"]),
    follow_up_questions: questions(BASIC_PET_FIELDS.concat(["neutered", "bodyCondition", "activityLevel"])),
    safety_notes: ["Weight loss should be gradual and monitored.", ...noDiagnosis],
    response_sections: ["calorie_frame", "food_shortlist", "satiety_signals", "treats"],
    eligible_logic: ["Boost weight control, light, satiety, higher fiber, adequate protein, lower kcal density."],
    rejected_logic: ["Avoid high calorie/high fat foods for weight-loss goal unless vet-directed."],
    confidence_rules: ["High confidence needs weight, body condition, kcal, protein, fat, and fiber.", ...sourceConfidenceRules],
  }),
  portion_size: template({
    intent: "portion_size",
    intent_group: "feeding",
    required_pet_fields: BASIC_PET_FIELDS.concat(["activityLevel", "neutered", "currentFood"]),
    follow_up_questions: questions(BASIC_PET_FIELDS.concat(["activityLevel", "neutered", "currentFood"])),
    safety_notes: ["Portions are estimates and should be adjusted by body condition and weight trend."],
    response_sections: ["daily_calories", "grams_per_day", "meals", "monitoring"],
    eligible_logic: ["Use kcal/100g or kcal/kg from database when available."],
    rejected_logic: ["Do not calculate grams without calories for the food."],
    confidence_rules: ["High confidence requires accurate weight and kcal data.", ...sourceConfidenceRules],
  }),
  food_transition: template({
    intent: "food_transition",
    intent_group: "feeding",
    required_pet_fields: ["species", "healthIssues", "currentFood"],
    follow_up_questions: questions(["species", "healthIssues", "currentFood"]),
    safety_notes: ["Go slower for sensitive digestion; stop and call vet if severe symptoms appear."],
    response_sections: ["transition_schedule", "what_to_watch", "when_to_pause"],
    eligible_logic: ["Default gradual transition over several days."],
    rejected_logic: ["Avoid abrupt switch unless veterinarian instructs it."],
    confidence_rules: ["Higher confidence when current and target foods are known."],
  }),
  puppy_growth: template({
    intent: "puppy_growth",
    intent_group: "life_stage",
    required_pet_fields: ["species", "age", "weight", "breed"],
    follow_up_questions: questions(["species", "age", "weight", "breed"]),
    safety_notes: ["Large-breed puppies need careful calcium/phosphorus and energy decisions.", ...noDiagnosis],
    response_sections: ["growth_fit", "large_breed_notes", "dha_note", "feeding_frequency"],
    eligible_logic: ["Use puppy/junior foods, large-breed fit when relevant, calcium/phosphorus data, DHA if available."],
    rejected_logic: ["Reject adult-only foods for puppies unless vet-directed.", "Hold large-breed puppy foods missing Ca/P."],
    confidence_rules: ["High confidence requires growth stage, size, calories, calcium and phosphorus.", ...sourceConfidenceRules],
  }),
  kitten_growth: template({
    intent: "kitten_growth",
    intent_group: "life_stage",
    required_pet_fields: ["species", "age", "weight"],
    follow_up_questions: questions(["species", "age", "weight"]),
    safety_notes: ["Kittens need growth-appropriate complete foods.", ...noDiagnosis],
    response_sections: ["kitten_fit", "energy_need", "dha_note", "feeding_frequency"],
    eligible_logic: ["Use kitten/growth foods and complete diets."],
    rejected_logic: ["Reject adult-only foods for kittens unless vet-directed."],
    confidence_rules: ["High confidence requires kitten life stage and calorie data.", ...sourceConfidenceRules],
  }),
  senior: template({
    intent: "senior",
    intent_group: "life_stage",
    required_pet_fields: BASIC_PET_FIELDS.concat(["healthIssues"]),
    follow_up_questions: questions(BASIC_PET_FIELDS.concat(["healthIssues"])),
    safety_notes: ["Senior weight loss, poor appetite, vomiting, or weakness needs vet review.", ...noDiagnosis],
    response_sections: ["senior_fit", "body_condition", "protein_energy", "watchouts"],
    eligible_logic: ["Boost senior/mature formulas when pet age fits and health context supports it."],
    rejected_logic: ["Do not assume senior needs weight loss or low protein without context."],
    confidence_rules: sourceConfidenceRules,
  }),
  active_working: template({
    intent: "active_working",
    intent_group: "feeding",
    required_pet_fields: BASIC_PET_FIELDS.concat(["activityLevel"]),
    follow_up_questions: questions(BASIC_PET_FIELDS.concat(["activityLevel"])),
    safety_notes: ["Condition and workload should guide calorie increases."],
    response_sections: ["energy_need", "food_fit", "monitoring"],
    eligible_logic: ["Boost active/performance and higher calorie foods when workload is truly high."],
    rejected_logic: ["Avoid high-energy foods for low activity pets."],
    confidence_rules: ["High confidence needs activity context and kcal data.", ...sourceConfidenceRules],
  }),
  treats: template({
    intent: "treats",
    intent_group: "feeding",
    required_pet_fields: BASIC_PET_FIELDS.concat(["bodyCondition"]),
    follow_up_questions: questions(BASIC_PET_FIELDS.concat(["bodyCondition"])),
    safety_notes: ["Treat calories usually should stay limited, especially for weight control."],
    response_sections: ["treat_limit", "safe_options", "what_to_avoid"],
    eligible_logic: ["Prefer simple, species-safe treats and account for calories."],
    rejected_logic: ["Reject toxic foods and treats conflicting with allergies."],
    confidence_rules: ["Higher confidence when daily calories and treat kcal are known."],
  }),
  supplements: template({
    intent: "supplements",
    intent_group: "medical",
    required_pet_fields: BASIC_PET_FIELDS.concat(["healthIssues"]),
    follow_up_questions: questions(BASIC_PET_FIELDS.concat(["healthIssues"])),
    safety_notes: ["Supplements can interact with disease and medication; vet advice matters.", ...noDiagnosis],
    response_sections: ["need_check", "food_first", "vet_note"],
    eligible_logic: ["Discuss general supplement purpose only."],
    rejected_logic: ["Do not prescribe doses or treatments."],
    confidence_rules: ["Low confidence without diagnosis, medication context, and diet details."],
  }),
  urinary: template({
    intent: "urinary",
    intent_group: "medical",
    required_pet_fields: BASIC_PET_FIELDS.concat(["vetDiagnosis"]),
    follow_up_questions: questions(BASIC_PET_FIELDS.concat(["vetDiagnosis"])),
    safety_notes: ["Male cat straining or no urine is an emergency.", ...noDiagnosis],
    response_sections: ["red_flag_check", "urinary_diet_logic", "minerals", "vet_note"],
    eligible_logic: ["Prefer urinary/veterinary formulas with magnesium, phosphorus, sodium data when available."],
    rejected_logic: ["Do not rely on magnesium alone.", "Hold casual recommendations for suspected blockage."],
    confidence_rules: ["High confidence requires confirmed urinary context and mineral data.", ...sourceConfidenceRules],
  }),
  sterilised: template({
    intent: "sterilised",
    intent_group: "feeding",
    required_pet_fields: BASIC_PET_FIELDS.concat(["neutered", "bodyCondition"]),
    follow_up_questions: questions(BASIC_PET_FIELDS.concat(["neutered", "bodyCondition"])),
    safety_notes: ["Sterilised pets often need calorie awareness, not automatic restriction."],
    response_sections: ["calorie_need", "food_shortlist", "body_condition_monitoring"],
    eligible_logic: ["Boost sterilised/light/satiety foods when pet is neutered and weight risk exists."],
    rejected_logic: ["Avoid assuming every sterilised pet needs weight-loss food."],
    confidence_rules: ["High confidence needs neuter status, weight, body condition, and kcal data.", ...sourceConfidenceRules],
  }),
  hairball: template({
    intent: "hairball",
    intent_group: "medical",
    required_pet_fields: ["species", "age", "healthIssues"],
    follow_up_questions: questions(["species", "age", "healthIssues"]),
    safety_notes: ["Repeated vomiting or appetite loss is not just hairball management.", ...noDiagnosis],
    response_sections: ["hairball_fit", "fiber_support", "red_flags"],
    eligible_logic: ["Boost cat hairball formulas and fiber-support signals."],
    rejected_logic: ["Do not frame persistent vomiting as normal hairballs."],
    confidence_rules: sourceConfidenceRules,
  }),
  fussy_eater: template({
    intent: "fussy_eater",
    intent_group: "behavior",
    required_pet_fields: ["species", "age", "currentFood", "healthIssues"],
    follow_up_questions: questions(["species", "age", "currentFood", "healthIssues"]),
    safety_notes: ["Not eating, especially cats, needs urgent vet guidance."],
    response_sections: ["palatability_options", "transition", "when_to_worry"],
    eligible_logic: ["Use flavor preferences and palatability clues; avoid allergy conflicts."],
    rejected_logic: ["Do not recommend waiting if pet is not eating."],
    confidence_rules: ["Higher confidence when current food, appetite pattern, and health context are known."],
  }),
  unclear_message: template({
    intent: "unclear_message",
    intent_group: "unclear",
    required_pet_fields: ["species"],
    follow_up_questions: questions(["species"]),
    safety_notes: ["Ask one clarifying question."],
    response_sections: ["clarify"],
    eligible_logic: ["Ask for the minimum next detail."],
    rejected_logic: ["Do not dump a full intake form."],
    confidence_rules: ["Low confidence until intent is clear."],
  }),
  medical_red_flag: template({
    intent: "medical_red_flag",
    intent_group: "medical",
    required_pet_fields: ["species"],
    follow_up_questions: questions(["species"]),
    safety_notes: ["Hard stop shopping mode and recommend veterinarian/emergency care."],
    response_sections: ["urgent_warning", "why", "what_to_do_now"],
    eligible_logic: ["Only safety guidance, no product recommendation."],
    rejected_logic: ["Reject normal shopping flow when red flags are present."],
    confidence_rules: ["High confidence red flag if user states no urine, collapse, blood, severe pain, not eating, or persistent vomiting."],
  }),
  photo_grounding: template({
    intent: "photo_grounding",
    intent_group: "evidence",
    required_pet_fields: ["species"],
    follow_up_questions: questions(["species"]),
    safety_notes: ["Photos support evidence but still need review if blurry or incomplete."],
    response_sections: ["what_to_photo", "fields_to_extract", "confidence"],
    eligible_logic: ["Ask for front, ingredients, analytical constituents, calories, barcode, pack size."],
    rejected_logic: ["Do not infer missing nutrients from unreadable photos."],
    confidence_rules: ["High confidence requires clear label panels and matched formula identity."],
  }),
  sales_checkout: template({
    intent: "sales_checkout",
    intent_group: "sales",
    required_pet_fields: ["species", "age", "weight", "healthIssues", "allergies"],
    follow_up_questions: questions(["species", "age", "weight", "healthIssues", "allergies"]),
    safety_notes: ["Commercial guidance must not override pet fit or medical safety."],
    response_sections: ["recommended_options", "budget_tradeoffs", "transition", "final_check"],
    eligible_logic: ["Offer premium and value options that fit the pet, not sponsor-only ranking."],
    rejected_logic: ["Reject foods excluded by safety, species, life stage, or allergy rules."],
    confidence_rules: sourceConfidenceRules,
  }),
};

export function getDialogueTemplate(intent: ChatbotIntent) {
  return dialoguePlaybook[intent] ?? dialoguePlaybook.unclear_message;
}
