export type PetAnalysisHistory = {
  id: string;
  petId: string;
  ownerId: string;
  rer: number;
  mer: number;
  recommendedFoodIds: string[];
  notes?: string;
  weight?: number;
  age?: number;
  activityLevel?: string;
  neutered?: boolean;
  allergies: string[];
  healthIssues: string[];
  food_score?: number | null;
  matched_food_id?: string | null;
  matched_food_name?: string | null;
  feeding_grams_per_day?: number | null;
  weight_goal?: string | null;
  createdAt: string;
};
