export type DbPetAnalysis = {
  id: string;
  pet_id: string;
  owner_id: string;
  rer: number;
  mer: number;
  recommended_food_ids: string[];
  notes: string | null;
  weight: number | null;
  age: number | null;
  activity_level: string | null;
  neutered: boolean | null;
  allergies: string[];
  health_issues: string[];
  food_score?: number | null;
  matched_food_id?: string | null;
  matched_food_name?: string | null;
  feeding_grams_per_day?: number | null;
  weight_goal?: string | null;
  created_at: string;
};
