import { NextResponse } from "next/server";
import { requireAdminApiAccess } from "@/lib/auth/adminApiGuard";

function csvCell(value: string | number) {
  return `"${String(value).replace(/"/g, '""')}"`;
}

export async function GET() {
  const forbidden = await requireAdminApiAccess();
  if (forbidden) return forbidden;

  const headers = [
    "brand",
    "formula_name",
    "display_name",
    "species",
    "format",
    "life_stage",
    "dog_size",
    "breed_target",
    "medical_tags",
    "commercial_tags",
    "ingredient_text",
    "ingredients",
    "primary_animal_proteins",
    "carbohydrate_sources",
    "fat_sources",
    "fiber_sources",
    "additives_text",
    "feeding_guide_text",
    "kcal_per_100g",
    "kcal_per_kg",
    "protein_percent",
    "fat_percent",
    "fiber_percent",
    "ash_percent",
    "moisture_percent",
    "calcium_percent",
    "phosphorus_percent",
    "sodium_percent",
    "magnesium_percent",
    "potassium_percent",
    "omega3_percent",
    "omega6_percent",
    "dha_percent",
    "epa_percent",
    "epa_dha_percent",
    "taurine_mgkg",
    "l_carnitine_mgkg",
    "glucosamine_mgkg",
    "chondroitin_mgkg",
    "vitamin_a_iukg",
    "vitamin_d3_iukg",
    "vitamin_e_mgkg",
    "iron_mgkg",
    "zinc_mgkg",
    "copper_mgkg",
    "manganese_mgkg",
    "iodine_mgkg",
    "selenium_mgkg",
    "data_quality_status",
    "data_source_url",
    "source_priority",
    "source_notes",
    "formula_key",
    "ean",
  ];

  const exampleRow = [
    "Example Brand",
    "Adult Chicken Medium",
    "Example Brand Adult Chicken Medium",
    "dog",
    "dry",
    "adult",
    "medium",
    "",
    "digestive_support",
    "grain_free",
    "chicken meal, rice, beet pulp, chicken fat, minerals",
    "",
    "",
    "",
    "",
    "",
    "",
    "vitamin A, vitamin D3, zinc, copper",
    "See official feeding guide by weight and activity.",
    "380",
    "3800",
    "26",
    "14",
    "3",
    "7",
    "8",
    "1.2",
    "0.9",
    "0.35",
    "0.08",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "needs_review",
    "https://example.com/product",
    "official",
    "market=GR; basis=as-fed; source_kind=product_page",
    "",
    "5200000000000",
  ];

  const csv = [
    headers.join(","),
    exampleRow.map(csvCell).join(","),
  ].join("\n");

  return new NextResponse(csv, {
    status: 200,
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": 'attachment; filename="nutritail-food-v2-template.csv"',
    },
  });
}
